shared:
  ingress_domain: 'TYPE_HERE_YOUR_DOMAIN_NAME'
  image_registry:
    project_path: 'TYPE_HERE_URL_TO_YOUR_PERSONAL_REGISTRY/myproject/'
    username: 'TYPE_HERE_PERSONAL_REGISTRY_LOGIN'
    password: 'TYPE_HERE_PERSONAL_REGISTRY_PASSWORD'
  kubernetes_distribution: "" # To be passed only for OpenShift. Defaults to "".
#  ca_cert_data: | # To be passed if using custom certificates.
#      -----BEGIN CERTIFICATE-----
#      MIIFXzCCA0egAwIBAgIJAJYm37SFocjlMA0GCSqGSIb3DQEBDQUAMEY...
#      -----END CERTIFICATE-----

appliveview:
  ingressEnabled: "true"
appliveview_connector:
  backend:
    sslDisabled: "true"

ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.
excluded_packages:
  - learningcenter.tanzu.vmware.com
  - workshops.learningcenter.tanzu.vmware.com

#The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

#Below are the keys which may have default values set, but can be overridden.

profile: full # Can take iterate, build, run, view.
supply_chain: basic # Can take testing, testing_scanning.

ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
  registry:
    server: 'TYPE_HERE_URL_TO_YOUR_PERSONAL_REGISTRY' # Takes the value from shared section above by default, but can be overridden by setting a different value.
    repository: 'myproject/supply-chain' # Takes the value from shared section above by default, but can be overridden by setting a different value.
  gitops:
    ssh_secret: "" # Takes "" as value by default; but can be overridden by setting a different value.

contour:
  envoy:
    service:
      type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

cnrs:
  provider: local
  domain_name: 'TYPE_HERE_YOUR_DOMAIN_NAME'
  # Fix domain template for TSL certficates
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

buildservice:
  kp_default_repository: 'TYPE_HERE_URL_TO_YOUR_PERSONAL_REGISTRY/myproject/build-service'
  kp_default_repository_username: 'TYPE_HERE_PERSONAL_REGISTRY_LOGIN'
  kp_default_repository_password: 'TYPE_HERE_PERSONAL_REGISTRY_PASSWORD'


tap_gui:
  service_type: ClusterIP # If the shared.ingress_domain is set as above, this must be set to ClusterIP.
  ingressEnabled: 'true'
  ingressDomain: 'TYPE_HERE_YOUR_DOMAIN_NAME'
  app_config:
    app:
        baseUrl: http://tap-gui.'TYPE_HERE_YOUR_DOMAIN_NAME'
    integrations:
      github:
        - host: github.com
          token: 'GITHUB_PERSONAL_TOKEN''
    catalog:
      locations:
        - type: url
          target: 'https://github.com/fklein82/tap-catalog/blob/main/catalog-info.yaml'
    backend:
        baseUrl: http://tap-gui.'TYPE_HERE_YOUR_DOMAIN_NAME'
        cors:
            origin: http://tap-gui.'TYPE_HERE_YOUR_DOMAIN_NAME'

metadata_store:
  ns_for_export_app_cert: "dev"
  app_service_type: ClusterIP

scanning:
  metadataStore:
    url: "" # Configuration is moved, so set this string to empty.

grype:
  namespace: "dev"
  targetImagePullSecret: "registry-credentials"


api_portal:
  apiPortalServer:
    sourceUrls: "https://petstore.swagger.io/v2/swagger.json,https://petstore3.swagger.io/api/v3/openapi.json"

