---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: sarycom
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: sarycom
  namespace: dev
spec:
  build:
    env:
    - name: BP_WEB_SERVER
      value: httpd
    - name: BP_WEB_SERVER_ROOT
      value: .
    - name: BP_WEB_SERVER_ENABLE_PUSH_STATE
      value: "true"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/fklein82/sarycom
